### POST generate a recipe from ingrediens
POST {{host}}:{{port}}/api/v1/ai/recipe
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ingredients": [
    {
      "name": "Tomates",
      "quantity": 4,
      "unit": "tomates"
    },
    {
      "name": "Oeufs",
      "quantity": 4,
      "unit": "Oeufs"
    },
    {
      "name": "Oignon",
      "quantity": 1,
      "unit": "oignon"
    },
    {
      "name": "Sel",
      "quantity": 10,
      "unit": "grammes"
    },
    {
      "name": "Fines herbes",
      "quantity": 50,
      "unit": "grammes"
    }
  ]
}


### POST generate recipe title from ingrediens
POST {{host}}:{{port}}/api/v1/ai/recipeTitle
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "ingredients": [
    {
      "name": "Tomates",
      "quantity": 4,
      "unit": "tomates"
    },
    {
      "name": "Oeufs",
      "quantity": 4,
      "unit": "Oeufs"
    },
    {
      "name": "Oignon",
      "quantity": 1,
      "unit": "oignon"
    },
    {
      "name": "Sel",
      "quantity": 10,
      "unit": "grammes"
    },
    {
      "name": "Fines herbes",
      "quantity": 50,
      "unit": "grammes"
    }
  ]
}


### POST a image to image in order to recieve titles for recipe
POST {{host}}:{{port}}/api/v1/ai/recipeTitle/image
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="product.png"
Content-Type: image/png

< C:/Users/thoma/Downloads/product.png
------boundary--


### POST a image to image in order to recieve a FULL recipe
POST {{host}}:{{port}}/api/v1/ai/recipe/image
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="product.png"
Content-Type: image/png

< C:/Users/thoma/Downloads/product.png
------boundary--