### POST Register
POST {{host}}:{{port}}/api/v1/recipe
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Test name 1",
  "durationMinutes": 50,
  "isFavorite": false,
  "ingredients": [
    {
      "name":"Patate",
      "quantity": 3,
      "unit": "unite"
    },
    {
      "name":"Farine",
      "quantity": 500,
      "unit": "gr"
    },
    {
      "name":"Eau",
      "quantity": 800,
      "unit": "ml"
    }
  ],
  "steps": [
    {
      "stepNumber": 1,
      "description": "Couper pomme de terre"
    },
    {
      "stepNumber": 2,
      "description": "Couper les tomates"
    },
    {
      "stepNumber": 3,
      "description": "Mettre au four"
    }
  ]
}

### GET recipe by id
GET {{host}}:{{port}}/api/v1/recipe/1
Authorization: Bearer {{token}}

### GET all recipes for a user
GET {{host}}:{{port}}/api/v1/recipe/all
Authorization: Bearer {{token}}

### GET all favorite recipes
GET {{host}}:{{port}}/api/v1/recipe/favorites
Authorization: Bearer {{token}}

### PATCH switch favorite recipe
PATCH {{host}}:{{port}}/api/v1/recipe/1
Authorization: Bearer {{token}}