### POST Register
POST http://localhost:8080/api/v1/recipe
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2Mjc5NTkwOCwiZXhwIjoxNzYyNzk5NTA4fQ.3HtrOLLJs2hiN9EP36LjXghDyf2vlnLtWqLlYJLiRtc
Content-Type: application/json

{
  "name": "Test name",
  "durationMinutes": 50,
  "isFavorite": false,
  "ingredients": [
    {
      "name":"Patate",
      "quantity": 5,
      "unit": "unite"
    },
    {
      "name":"Farine",
      "quantity": 500,
      "unit": "gr"
    },
    {
      "name":"Eau",
      "quantity": 200,
      "unit": "ml"
    }
  ],
  "steps": [
    {
      "stepNumber": 1,
      "description": "Couper pomme de terre"
    },
    {
      "stepNumber": 2,
      "description": "Couper les tomates"
    },
    {
      "stepNumber": 3,
      "description": "Mettre au four"
    }
  ]
}

### GET
http://localhost:8080/api/v1/recipe/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc2Mjc5Njc5MCwiZXhwIjoxNzYyODAwMzkwfQ.OXD8fadXNsnezsx3SU_9bQ6Bb-epNMqlXnHMRoBHMUI