### GET shoppingList by id
GET {{host}}:{{port}}/api/v1/shopping/1
Authorization: Bearer {{token}}

### GET all shopping list for a user
GET {{host}}:{{port}}/api/v1/shopping
Authorization: Bearer {{token}}

### Delete an shopping list for a user
DELETE {{host}}:{{port}}/api/v1/shopping/1
Authorization: Bearer {{token}}

### Create an shopping list for a user
POST {{host}}:{{port}}/api/v1/shopping
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "shoppingListName": "Courses TEST created",
  "creationDate": "2025-01-15T10:30:00",
  "items": [
    {
      "name": "Pommes",
      "quantity": 6,
      "unit": "pieces",
      "sequence": 1
    },
    {
      "name": "Lait",
      "quantity": 2,
      "unit": "litres",
      "sequence": 2
    },
    {
      "name": "Pâtes",
      "quantity": 1,
      "unit": "kg",
      "sequence": 3
    }
  ]
}

### Create an shopping list for a user
PUT {{host}}:{{port}}/api/v1/shopping
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 4,
  "shoppingListName": "Courses TEST update",
  "creationDate": "2025-01-15T10:30:00",
  "items": [
    {
      "name": "Pommes updated",
      "quantity": 6,
      "unit": "pieces",
      "sequence": 1
    },
    {
      "name": "Lait",
      "quantity": 999,
      "unit": "litres",
      "sequence": 2
    },
    {
      "name": "Pâtes",
      "quantity": 1,
      "unit": "gr",
      "sequence": 3
    }
  ]
}

### add an item in a shopping list for a user
POST {{host}}:{{port}}/api/v1/shopping/item/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "ajout d'un truc",
  "quantity": 6,
  "unit": "pieces",
  "sequence": 1
}

### add an item list in a shopping list for a user
POST {{host}}:{{port}}/api/v1/shopping/item/list/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "items": [
    {
      "name": "ajout d'un truc",
      "quantity": 6,
      "unit": "pieces",
      "sequence": 1
    },
    {
      "name": "ajout d'un autre truc",
      "quantity": 88,
      "unit": "pieces",
      "sequence": 1
    }
  ]
}