### GET preference by user id
GET {{host}}:{{port}}/api/v1/user/preferences
Authorization: Bearer {{token}}

### POST add preferences
POST {{host}}:{{port}}/api/v1/user/preferences
Authorization: Bearer {{token}}
Content-Type: application/json

[
  { "allergen": "PECHE" }
]

### GET setting by user id
GET {{host}}:{{port}}/api/v1/user/settings
Authorization: Bearer {{token}}


### PUT setting for user id
PUT {{host}}:{{port}}/api/v1/user/settings
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "darkMode": null,
    "nbPeople": 3,
    "language": null
}

