### GET preference by user id
GET {{host}}:{{port}}/api/v1/user/preferences
Authorization: Bearer {{token}}

### POST add preferences
POST {{host}}:{{port}}/api/v1/user/preferences
Authorization: Bearer {{token}}
Content-Type: application/json

[
  { "allergen": "PECHE" }
]

### DELETE preference for a user by preference name
DELETE {{host}}:{{port}}/api/v1/user/preference/name/GLUTEN
Authorization: Bearer {{token}}

### DELETE preference for a user by preference id
DELETE {{host}}:{{port}}/api/v1/user/preference/id/2
Authorization: Bearer {{token}}

### GET setting by user id
GET {{host}}:{{port}}/api/v1/user/settings
Authorization: Bearer {{token}}


### PUT setting for user id
PUT {{host}}:{{port}}/api/v1/user/settings
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "darkMode": null,
    "nbPeople": 3,
    "language": null
}

